import { NextResponse } from 'next/server';
import pool from '@/lib/db';

export const dynamic = 'force-dynamic';

export async function POST(req: Request) {
  try {
    const payload = await req.json();
    const { orderId, labStatus, riderName, riderPhone, reportUrl } = payload;

    if (!orderId) {
      return NextResponse.json({ success: false, error: 'Order ID is required' }, { status: 400 });
    }

    // 1. Fetch Patient details
    const orderRes = await pool.query(
      `SELECT customer_name, customer_phone, customer_email, lab_assigned FROM orders WHERE order_id = $1`,
      [orderId]
    );

    if (orderRes.rows.length === 0) {
      return NextResponse.json({ success: false, error: 'Order not found' }, { status: 404 });
    }

    const order = orderRes.rows[0];
    const cleanPhone = String(order.customer_phone).replace(/\D/g, '').slice(-10);

    let nextStatus = labStatus || 'PROCESSING';
    let dispatchedAt = null;
    let dispatchChannel = null;

    // 2. If Report is Generated by Lab -> Trigger Auto WhatsApp & Email Dispatch
    if (reportUrl) {
      nextStatus = 'REPORT_READY';
      dispatchedAt = new Date().toISOString();
      dispatchChannel = 'WHATSAPP_AUTO_DISPATCH';

      // WhatsApp Cloud API / Gateway message payload
      const waMsg = `Namaste ${order.customer_name},\n\nAapki *${order.lab_assigned}* dwara kiye gaye diagnostic test ki verified digital report taiyar hai! 📄\n\nDirect Download Report Link:\n${reportUrl}\n\nHealth advice ya re-test ke liye TestBeat Medical Advisor se sampark karein.\n- TestBeat Diagnostics`;

      // In production, invoke WhatsApp Cloud API or WATI/Gupshup webhook here:
      console.log(`[AUTO-DISPATCH] Sent report to WhatsApp: +91${cleanPhone}`);
    }

    // 3. Update Order in Neon DB
    await pool.query(
      `UPDATE orders 
       SET fulfillment_status = $1,
           lab_rider_name = COALESCE($2, lab_rider_name),
           lab_rider_phone = COALESCE($3, lab_rider_phone),
           report_pdf_url = COALESCE($4, report_pdf_url),
           report_dispatched_at = COALESCE($5, report_dispatched_at),
           dispatch_channel = COALESCE($6, dispatch_channel)
       WHERE order_id = $7`,
      [nextStatus, riderName || null, riderPhone || null, reportUrl || null, dispatchedAt, dispatchChannel, orderId]
    );

    return NextResponse.json({
      success: true,
      message: `Order status synced to ${nextStatus}`,
      autoDispatched: !!reportUrl
    });

  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
